import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Doctor Appointment App",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.className}  antialiased`}>
        <div className="md:px-20">
          <Header />

          {children}
        </div>
      </body>
    </html>
  );
}
